In [3]:
import pandas as pd

# Input File
amr_data = "/home/nvinden/School/CIS4020/kkinds_ABR/data/full_data_NY/AMR_Data.csv"
save_name = "/home/nvinden/School/CIS4020/kkinds_ABR/data/full_data_NY/assay_keys.csv"

In [4]:
df = pd.read_csv(amr_data)

/tmp/ipykernel_14106/328467993.py:1: DtypeWarning: Columns (53,54,55,57,58,60,62,69,70) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(amr_data)

,Unnamed: 0,id,state,county,zip_3_level,order_year,order_month,species,panel_name,assay_name,...,CEFIXIME,CEFOXITIN,ANIDULAFUNGIN,CEFIPIME,CLARITHROMYCIN,KANAMYCIN,NOVOBIOCIN,PIPERACILLIN,SULFAMETHOXAZOLE,TICARCILLINCLAVULANIC ACID
0,126299,0.789887864830128.1,New York,New York,100,2022,5,CANINE,URINE CULT & SUSCEPTIBILITY,URINE CULTURE RESULTS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,126300,0.789887864830128.2,New York,New York,100,2022,5,CANINE,URINE CULT & SUSCEPTIBILITY,URINE CULTURE RESULTS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,126301,0.980109596269822.1,New York,New York,100,2022,9,CANINE,AEROBIC CULTURE,Aerobic Culture,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,126302,0.980109596269822.2,New York,New York,100,2022,9,CANINE,AEROBIC CULTURE,Aerobic Culture,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,126303,0.205133129466774.1,New York,New York,100,2022,5,CANINE,URINE CULT & SUSCEPTIBILITY,URINE CULTURE RESULTS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111964,1463545,0.149126824343345.1,New York,Chemung,149,2021,12,CANINE,AEROBIC EAR CULTURE,Aerobic Culture,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111965,1463546,0.511904009405761.1,New York,Chemung,149,2021,12,CANINE,URINE CULT & SUSCEPTIBILITY,URINE CULTURE RESULTS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111966,1463547,0.246729419755852.1,New York,Chemung,149,2021,12,CANINE,URINE CULT & SUSCEPTIBILITY,URINE CULTURE RESULTS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111967,1463548,0.0822386402928423.1,New York,Chemung,149,2021,12,CANINE,URINE CULT & SUSCEPTIBILITY,URINE CULTURE RESULTS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111968,1463549,0.190794418508027.1,New York,Chemung,149,2021,12,CANINE,URINE CULT & SUSCEPTIBILITY,URINE CULTURE RESULTS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
# Get all unique assay names
assay_names = df['assay_name'].unique()

# Create a DataFrame with these unique names in both columns
# You need to ensure the data is structured correctly to create the two columns
assay_df = pd.DataFrame({'assay_name': assay_names, 'assay_cat': assay_names})

# Replace empty strings with "UNKNOWN"
assay_df = assay_df.replace(r'^\s*$', 'UNKNOWN', regex=True)

# Save the dataframe
assay_df.to_csv(save_name, index=False)

assay_df

                  assay_name                 assay_cat
0      URINE CULTURE RESULTS     URINE CULTURE RESULTS
1            Aerobic Culture           Aerobic Culture
2          Aerobic Culture 2         Aerobic Culture 2
3        Environment Culture       Environment Culture
4          Pre Breed Culture         Pre Breed Culture
5    Aerobic Culture ID Only   Aerobic Culture ID Only
6              Fecal Culture             Fecal Culture
7      Blood Culture Aerobic     Blood Culture Aerobic
8    Blood Culture 2 Aerobic   Blood Culture 2 Aerobic
9     MRSA Screening Culture    MRSA Screening Culture
10  Yersinia Cold Enrichment  Yersinia Cold Enrichment
11   Blood Culture 3 Aerobic   Blood Culture 3 Aerobic